### PR TITLE
Implement reverse ordering for u32/u64

### PR DESCRIPTION
**Pull request by mneumann**
This allows reverse ordering in a simple way. Maybe name "-u32" to "u32_desc"? If accepted, I will come up with some test cases. I have some in rust-sophia already.

### CODE REVIEW

**Comment by pmwkaa** [comment]
This patch looks nice, but i cant get an idea how this can be really used.
Let assume we store keys: 1, 2, 3.
We always can iterate them in reverse order using cursor (order field set to <, <=).
What am i missing? :)

**Comment by mneumann** [comment]
hm, I was thinking that the values are layed out sequentially on disk, so that a forward scan will be generally faster than a backward scan (page prefetching etc.).

**Comment by pmwkaa** [comment]
I got your point) maybe u32_rev? it will be easier for me to write tests, since i'm about to upgrade test suite one of these days

**Comment by mneumann** [comment]
```u32_rev``` is prefect :)

**Pull request merged**
