### PR TITLE
makefile: Consider `sophia.{c,h}` dirty when their deps change

### PR DESCRIPTION
**Pull request by stephenmathieson**
I should have done this in #63. :/

### CODE REVIEW

**Comment by pmwkaa** [comment]
I think this is ok to rebuild sophia.c every time and not depend on $(SOPHIA_SRC). sophia/build script tries to get current git version which could change, even if no C files changed. This git version is used for "sophia.build" ctl.

It would be nice to have make -j support, but i couldn't yet got idea how to make it correctly with clean. Probably better to call '$(MAKE) target' from make itself? :)

**Comment by pmwkaa** [comment]
https://travis-ci.org/pmwkaa/sophia/jobs/49174319#L356

**Comment by stephenmathieson** [comment]
oh, i didn't realise the build scripts checks git.  that's very clever.

**Comment by saghul** [comment]
> It would be nice to have make -j support, but i couldn't yet got idea how to make it correctly with clean. Probably better to call '$(MAKE) target' from make itself? :)

I'm not sure that will be possible since now you're compiling a single big file.

**Comment by KenanSulayman** [comment]
Is there an update on this PR?

**Comment by rtsisyk** [comment]
Tarantool also has problem with rebuilding sophia.c.

**Comment by pmwkaa** [comment]
Sorry guys for delay, considering this PR merged by the commit.

**Comment by stephenmathieson** [comment]
Cool, thanks!!

**Pull request closed without merging**
